[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7"
serde_json = "1.0.89"
serde = { version = "1.0.150", features = ["derive"] }
cute = "0.3.0"
